# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('brand', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('subtype', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('available', models.BooleanField()),
                ('special', models.BooleanField()),
                ('UID', models.IntegerField()),
                ('number_sold', models.IntegerField()),
                ('quantity_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('max_number_of_customer_at_one_time', models.CharField(max_length=250)),
                ('working_driver', models.CharField(max_length=250)),
                ('date_created', models.CharField(max_length=250)),
                ('UID', models.CharField(max_length=250)),
                ('is_deleted', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=250)),
                ('contact_first', models.CharField(max_length=250)),
                ('contact_last', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='alcohol',
            name='stores',
            field=models.ManyToManyField(to='storage.store'),
        ),
    ]
