# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='UID',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_first',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_last',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='date_created',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='discription',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_deleted',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_number_of_customer_at_one_time',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_driver',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
