# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20170219_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='Type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='UID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='available',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='brand',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='number_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='origin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='price',
            field=models.FloatField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='quantity_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='special',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='subtype',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
